Repository RMartin0717/fitlit, pull requests merged in 2021-03, with the labels that each got.

#10 Feature/data and users
  package-lock.json
  package.json
  src/User.js
  src/UserRepository.js
  test/User-tests.js
  test/UserRepository-tests.js
Labels: Iteration 1, class build

#9 Feature/css
  index.html
  style.css
Labels: Iteration 1, dashboard, styling

#13 Display name, info card, and step goal to the DOM
  index.html
  src/User.js
  src/UserRepository.js
  src/index.html
  src/scripts.js
Labels: Iteration 1, dashboard
