Repository RMartin0717/fitlit, pull requests merged in 2021-04, with the labels that each got.

#26 Feature/sleep classes
  src/AllUserSleep.js
  src/UserSleep.js
  test/AllUserSleep-tests.js
  test/UserSleep-tests.js
Labels: Iteration 3, TDD, class build

#31 Refactor/helper methods
  src/AllUserSleep.js
  src/Hydration.js
  src/UserSleep.js
  src/helpers/calcAverage.js
  src/helpers/formatDataByDate.js
  src/helpers/retrieveDataByWeek.js
  test/AllUserSleep-tests.js
  test/Hydration-test.js
Labels: refactor

#46 Feature/chart js
  index.html
  package-lock.json
  package.json
  src/scripts.js
  style.css
Labels: dashboard, enhancement, styling

#44 Dom/display sleep data
  index.html
  src/Hydration.js
  src/UserSleep.js
  src/scripts.js
Labels: Iteration 3, dashboard

#48 Feature/chart js
  index.html
  src/scripts.js
  style.css
Labels: css, dashboard, styling

#49 Feature/chart js
  index.html
  src/scripts.js
  style.css
Labels: css, dashboard

#50 Testing/class testing
  index.html
  src/AllUserSleep.js
  src/UserHydration.js
  src/UserSleep.js
  src/helpers/calcAverage.js
  src/helpers/dataForDay.js
  src/helpers/retrieveDataByWeek.js
  src/scripts.js
  test/AllUserSleep-tests.js
  test/Hydration-test.js
  test/User-tests.js
  test/UserSleep-tests.js
Labels: TDD, refactor

#51 Feature/css
  index.html
  src/scripts.js
  style.css
Labels: css, dashboard
